name: Docker image
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login into docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: image pull
        run: |
          docker pull ubuntu
          pwd
          ls -lrt
          
          
  
